### PR TITLE
Gnome 40

### PR DESCRIPTION
**Pull request by zweif**
Hi there,

I tried to port this extension to Gnome 40 (https://github.com/bellini666/gnome-shell-notifications-alert/issues/55).
My tests (Ubuntu 21.10) seemed to be fine, but since I'm new to Gnome extensions review is requested.
I couldn't replicate the look of the filter list toolbar in preferences, but it is working.
I also didn't test Gnome 41.
This likely breaks pre-40-compatibility, so I removed these versions.

### CODE REVIEW

**Comment by stefan6419846** [comment]
Has there been any progress on this? Is this still WIP without any activity in-between for 1.5 years now? At least in my case, everything seems to work correctly after installing this modified version, so making this available upstream without the need to manually install it appears to be the best approach.

**Comment by zweif** [comment]
I originally marked this as draft because I'm inexperienced in this stuff and it might need a little cleanup. And since there didn't seem to be much of an interest I left it as is. I'm still using it in Gnome 43 without modifications, except compatibility info.
Maybe @bellini666 can say something about this?

**Comment by bellini666** [comment]
Hey guys. I think that since this was marked as draft I was waiting for it to be finished before reviewing it :)

I'm actually not using my extension anymore, so I will take your word on the compatibility of gnome versions.

Btw, this is marked as compatible with gnome-shell 40 and 41. We now have 42, 43 and 44 is going to be released right now. @zweif do you know that with your changes this extension is/will be compatible with those versions? If so, you might want to add those versions to the manifest as well.

Regarding the changes, they all looks fine to me! Just take a look at the supported versions and I can merge and make a new release at ego

**Comment by zweif** [comment]
Hey @bellini666, thanks for your reply.
I used this from gnome-shell 40 to 43 without noticing any issues. Took a quick test now in Gnome OS Nightly (44) today and it seems fine :)

**Comment by bellini666** [comment]
Awesome! Thank you, going to merge and do a new release on ego

**Comment by bellini666** [comment]
Hey @zweif . The extension got reviewed and the reviewer asked for some changes: https://extensions.gnome.org/review/39483

Wondering if you want to adjust it?

**Comment by zweif** [comment]
That was fast. I'll have a look and see what I can do.

**Pull request merged**
